from os import system

print('Создать venv? <y/n>')
if input('>') == 'y':
	print('Создание venv')
	system('python -m venv venv')
print('Для последующей загрузки фалов и модулей активируйте venv и откройте этот скрипт там. Нажмите Enter, если вы активировали venv. Если нет, нажмите Ctrl+C и активируйте venv.')
input()
system('pip install aiogram==2.25.2')
print('Загрузка файла зависимостей')
system('pip freeze > requirements.txt')
print('Заполнение main.py и config.py')
fl = open('main.py', 'w+')
fl.write('from aiogram import Dispatcher, Bot, executor, types\n')
fl.write('from config import TOKEN\n')
fl.write('from logging import basicConfig, INFO\n\n')
fl.write('bot = Bot(token=TOKEN)\n')
fl.write('dp = Dispatcher(bot)\n')
fl.write('basicConfig(level=INFO)\n\n')
fl.write('#your code\n\n')
fl.write('executor.start_polling(dp)')
fl.close()
fl = open('config.py', 'w+')
fl.write('TOKEN = "" #your token')
fl.close()
print('Создать .gitignore? <y/n>')
if input('>') == 'y':
	print('Создание .gitignore')
	fl = open('.gitignore', 'w+')
	fl.write(r'\\venv\\ \n')
	fl.write('\\config.py\n')
	fl.write('\\__pycache__\\')
	fl.close()
print('Успешно!')